name: Test Github Action
on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different
  workflow_dispatch:

jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Check Newcahnges Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version
